### PR TITLE
Get all variables, not just first 20

### LINKED ISSUE #35: Pagination is not handled
If we have many variables, pagination is not handled in the response to process all variables. (X-Total-Pages)

### PR DESCRIPTION
**Pull request by bradym**
By default GitLab returns only the first 20 variables unless pagination is used on the API: https://docs.gitlab.com/ee/api/README.html#offset-based-pagination

This PR adds the required pagination.

I'm still fairly new to golang, so I'm very open to any feedback! :)

Fixes #35

### CODE REVIEW

**Comment by bradym** [comment]
Took me a minute to realize code climate isn't complaining about the _line_ it's showing me, but the function. I'll take a stab at breaking it up a bit tomorrow.

**Review by lingrino — COMMENTED** [review]
This is looking great, thank you for the contribution! I found https://github.com/xanzy/go-gitlab/blob/master/examples/pagination.go which looks like what you've done as well, the two suggestions are just to include the `ListOptions` nested struct.

You might consider creating a function for pagination. It could take in a function to run and return the result after everything is paginated. That may fix the code climate complaint. I'm also ok with leaving things as they are. I'll merge despite code climate if we need to.

I would also look at renaming `variablesPerPage` to `pageSize` and making it a `const` at the top of the file, but that's up to you and won't change functionality.

**Comment by bradym** [comment]
Thanks for the feedback! I did indeed find that pagination example and shamelessly copy it. :)

Here's what I did:

- Renamed `variablesPerPage` to `pageSize` and used a const, as suggested
- Created two functions: `getGroupVariables` and `getProjectVariables` that are called from `Init`
  - I thought about combining them to a single function, but it didn't seem worth the trouble for such simple code. 
- I tried including the nested `ListOptions` but I was getting errors with that in place. Looking at the code, it appears that the `ListGroupVariablesOptions` and `ListProjectVariablesOptions` structs don't have the nested struct like the one in the example. 

Let me know if there are any other changes you'd like to this PR.

**Review by lingrino — APPROVED** [review]
This is great, thank you! I will tag a `1.3.0` release. Looks like I need to update the validate action to work on forks so I'll do that first.

**Pull request merged**
